version: '3.9'
services:
  yolov8:
    build:
      context: . 
      dockerfile: Dockerfile
    runtime: nvidia
    image: yolov8:latest
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - PYTHONUNBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=all
