version: '3.9'
services:
  yolov8:
    build:
      context: . 
      dockerfile: Dockerfile
    image: yolov8:latest
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - ./data:/usr/src/app/data
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "-m", "ultralytics", "predict", "model=yolov8n.pt", "source=path/to/your/image.jpg"]
